"""
Oracle Schema Registry
DDL definitions for all SharePoint bridge tables.
5 tables: SPX_SITES, SPX_LISTS, SPX_ITEMS, SPX_DOCUMENTS, SPX_SYNC_LOG
"""

SCHEMA_DDL = """
-- ── SPX_SITES ─────────────────────────────────────────────────
-- One row per SharePoint site discovered
CREATE TABLE SPX_SITES (
  SITE_ID          VARCHAR2(200)  NOT NULL,
  DISPLAY_NAME     VARCHAR2(500)  NOT NULL,
  WEB_URL          VARCHAR2(2000) NOT NULL,
  DESCRIPTION      CLOB,
  OWNER_EMAIL      VARCHAR2(255),
  STORAGE_USED     NUMBER(15),
  SP_CREATED_AT    DATE,
  SP_MODIFIED_AT   DATE,
  SYNC_STATUS      VARCHAR2(20)   DEFAULT 'SYNCED',
  CREATED_AT       DATE           DEFAULT SYSDATE,
  UPDATED_AT       DATE           DEFAULT SYSDATE,
  CONSTRAINT SPX_SITES_PK PRIMARY KEY (SITE_ID)
);

-- ── SPX_LISTS ─────────────────────────────────────────────────
-- One row per SharePoint list / document library
CREATE TABLE SPX_LISTS (
  LIST_ID          VARCHAR2(200)  NOT NULL,
  SITE_ID          VARCHAR2(200)  NOT NULL,
  DISPLAY_NAME     VARCHAR2(500)  NOT NULL,
  DESCRIPTION      CLOB,
  LIST_TYPE        VARCHAR2(50),
  ITEM_COUNT       NUMBER(10)     DEFAULT 0,
  DELTA_TOKEN      VARCHAR2(500),
  LAST_SYNC_AT     DATE,
  SYNC_STATUS      VARCHAR2(20)   DEFAULT 'PENDING',
  SP_CREATED_AT    DATE,
  SP_MODIFIED_AT   DATE,
  CREATED_AT       DATE           DEFAULT SYSDATE,
  UPDATED_AT       DATE           DEFAULT SYSDATE,
  CONSTRAINT SPX_LISTS_PK  PRIMARY KEY (LIST_ID),
  CONSTRAINT SPX_LISTS_FK  FOREIGN KEY (SITE_ID) REFERENCES SPX_SITES(SITE_ID)
);

-- ── SPX_ITEMS ─────────────────────────────────────────────────
-- One row per SharePoint list item — flexible CLOB fields for any schema
CREATE TABLE SPX_ITEMS (
  ITEM_ID          VARCHAR2(200)  NOT NULL,
  LIST_ID          VARCHAR2(200)  NOT NULL,
  SITE_ID          VARCHAR2(200)  NOT NULL,
  SP_ETAG          VARCHAR2(100),
  TITLE            VARCHAR2(4000),
  STATUS           VARCHAR2(255),
  PRIORITY         VARCHAR2(100),
  ASSIGNED_TO      VARCHAR2(255),
  DUE_DATE         DATE,
  FIELDS_JSON      CLOB,            -- Full raw fields as JSON for flexibility
  SYNC_STATUS      VARCHAR2(20)    DEFAULT 'SYNCED',
  PUSH_PENDING     NUMBER(1)       DEFAULT 0,  -- 1 = needs push back to SharePoint
  SP_CREATED_AT    DATE,
  SP_MODIFIED_AT   DATE,
  SP_CREATED_BY    VARCHAR2(255),
  SP_MODIFIED_BY   VARCHAR2(255),
  CREATED_AT       DATE            DEFAULT SYSDATE,
  UPDATED_AT       DATE            DEFAULT SYSDATE,
  DELETED          NUMBER(1)       DEFAULT 0,
  CONSTRAINT SPX_ITEMS_PK  PRIMARY KEY (ITEM_ID),
  CONSTRAINT SPX_ITEMS_FK1 FOREIGN KEY (LIST_ID) REFERENCES SPX_LISTS(LIST_ID),
  CONSTRAINT SPX_ITEMS_FK2 FOREIGN KEY (SITE_ID) REFERENCES SPX_SITES(SITE_ID)
);

CREATE INDEX SPX_ITEMS_LIST_IDX    ON SPX_ITEMS(LIST_ID);
CREATE INDEX SPX_ITEMS_STATUS_IDX  ON SPX_ITEMS(STATUS);
CREATE INDEX SPX_ITEMS_PUSH_IDX    ON SPX_ITEMS(PUSH_PENDING) WHERE PUSH_PENDING = 1;

-- ── SPX_DOCUMENTS ─────────────────────────────────────────────
-- Document library files with extracted text
CREATE TABLE SPX_DOCUMENTS (
  DOC_ID           VARCHAR2(200)  NOT NULL,
  LIST_ID          VARCHAR2(200)  NOT NULL,
  SITE_ID          VARCHAR2(200)  NOT NULL,
  FILE_NAME        VARCHAR2(500)  NOT NULL,
  FILE_TYPE        VARCHAR2(20),
  FILE_SIZE        NUMBER(15),
  WEB_URL          VARCHAR2(2000),
  SP_ETAG          VARCHAR2(100),
  EXTRACTED_TEXT   CLOB,
  PAGE_COUNT       NUMBER(5),
  SYNC_STATUS      VARCHAR2(20)   DEFAULT 'SYNCED',
  SP_CREATED_AT    DATE,
  SP_MODIFIED_AT   DATE,
  SP_CREATED_BY    VARCHAR2(255),
  CREATED_AT       DATE           DEFAULT SYSDATE,
  UPDATED_AT       DATE           DEFAULT SYSDATE,
  CONSTRAINT SPX_DOCUMENTS_PK  PRIMARY KEY (DOC_ID),
  CONSTRAINT SPX_DOCUMENTS_FK1 FOREIGN KEY (LIST_ID) REFERENCES SPX_LISTS(LIST_ID),
  CONSTRAINT SPX_DOCUMENTS_FK2 FOREIGN KEY (SITE_ID) REFERENCES SPX_SITES(SITE_ID)
);

CREATE INDEX SPX_DOCUMENTS_LIST_IDX ON SPX_DOCUMENTS(LIST_ID);
CREATE INDEX SPX_DOCUMENTS_TYPE_IDX ON SPX_DOCUMENTS(FILE_TYPE);

-- ── SPX_SYNC_LOG ──────────────────────────────────────────────
-- Audit trail for every sync operation
CREATE TABLE SPX_SYNC_LOG (
  LOG_ID           NUMBER(10)     GENERATED ALWAYS AS IDENTITY,
  OPERATION        VARCHAR2(50)   NOT NULL,
  RESOURCE_ID      VARCHAR2(200),
  RESOURCE_TYPE    VARCHAR2(50),
  ITEMS_FOUND      NUMBER(10)     DEFAULT 0,
  ITEMS_CREATED    NUMBER(10)     DEFAULT 0,
  ITEMS_UPDATED    NUMBER(10)     DEFAULT 0,
  ITEMS_DELETED    NUMBER(10)     DEFAULT 0,
  ITEMS_FAILED     NUMBER(10)     DEFAULT 0,
  DLQ_COUNT        NUMBER(10)     DEFAULT 0,
  AVG_QUALITY      NUMBER(5,1),
  DURATION_MS      NUMBER(10),
  DELTA_TOKEN      VARCHAR2(500),
  ERROR_DETAIL     CLOB,
  DIRECTION        VARCHAR2(20)   DEFAULT 'SP_TO_ORACLE',  -- SP_TO_ORACLE | ORACLE_TO_SP
  STARTED_AT       DATE           DEFAULT SYSDATE,
  CONSTRAINT SPX_SYNC_LOG_PK PRIMARY KEY (LOG_ID)
);

CREATE INDEX SPX_SYNC_LOG_OP_IDX ON SPX_SYNC_LOG(OPERATION);
CREATE INDEX SPX_SYNC_LOG_DT_IDX ON SPX_SYNC_LOG(STARTED_AT);
"""

SAMPLE_DATA_SQL = """
-- Sample sites
INSERT INTO SPX_SITES (SITE_ID, DISPLAY_NAME, WEB_URL, OWNER_EMAIL, STORAGE_USED, SYNC_STATUS)
VALUES ('site-001','Acme Corp Intranet','https://acme.sharepoint.com/sites/intranet','admin@acme.com',734003200,'SYNCED');

INSERT INTO SPX_SITES (SITE_ID, DISPLAY_NAME, WEB_URL, OWNER_EMAIL, STORAGE_USED, SYNC_STATUS)
VALUES ('site-002','HR Portal','https://acme.sharepoint.com/sites/hr','hr@acme.com',1258291200,'SYNCED');

-- Sample lists
INSERT INTO SPX_LISTS (LIST_ID, SITE_ID, DISPLAY_NAME, LIST_TYPE, ITEM_COUNT, SYNC_STATUS)
VALUES ('list-001','site-001','Company Announcements','genericList',24,'SYNCED');

INSERT INTO SPX_LISTS (LIST_ID, SITE_ID, DISPLAY_NAME, LIST_TYPE, ITEM_COUNT, SYNC_STATUS)
VALUES ('list-004','site-002','Employee Directory','genericList',87,'SYNCED');

-- Sample items
INSERT INTO SPX_ITEMS (ITEM_ID,LIST_ID,SITE_ID,TITLE,STATUS,PRIORITY,ASSIGNED_TO,SYNC_STATUS,PUSH_PENDING)
VALUES ('item-list-001-0001','list-001','site-001','Q4 Planning Complete','Approved','High','alice@acme.com','SYNCED',0);

INSERT INTO SPX_ITEMS (ITEM_ID,LIST_ID,SITE_ID,TITLE,STATUS,PRIORITY,ASSIGNED_TO,SYNC_STATUS,PUSH_PENDING)
VALUES ('item-list-001-0002','list-001','site-001','Server Migration','InProgress','Critical','bob@acme.com','SYNCED',0);

-- Item with PUSH_PENDING — will be pushed back to SharePoint
INSERT INTO SPX_ITEMS (ITEM_ID,LIST_ID,SITE_ID,TITLE,STATUS,PRIORITY,SYNC_STATUS,PUSH_PENDING)
VALUES ('item-oracle-001','list-001','site-001','Q4 Payroll Run Complete','Complete','High','PENDING_PUSH',1);

COMMIT;
"""
